booksite/accounts/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login, logout
from .views import register, AddressListView, AddressCreateView, AddressUpdateView, AddressDeleteView, OrderListView, profile_detail, ProfileCreateView, ProfileUpdateView
urlpatterns = [
    url(r'^register/$', register, name='register'),          
    url(r'^login/$', login, name='login'),
    url(r'^logout/$', logout, name='logout'),
    url(r'^address/$', AddressListView.as_view(), name='address_list'),
    url(r'^address/new/$', AddressCreateView.as_view(), name='address_new'), 
    url(r'^address/(?P<pk>\d+)/edit/$', AddressUpdateView.as_view(), name='address_edit'),
    url(r'^address/(?P<pk>\d+)/delete/$', AddressDeleteView.as_view(), name='address_delete'),  
    url(r'^order/$', OrderListView.as_view(), name='order_list'), 
    url(r'^profile/new/$', ProfileCreateView.as_view(), name='profile_new'),
    url(r'^profile/edit/$', ProfileUpdateView.as_view(), name='profile_edit'),
    url(r'^profile/$',profile_detail,name='profile')     
               ]

booksite/booksite/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns = [
        url(r'^admin/', admin.site.urls),
        url(r'^books/', include('catalog.urls', namespace='catalog')),
        url(r'^accounts/', include('accounts.urls', namespace='accounts')),
        url(r'^cart/', include('cart.urls', namespace= 'cart')),
        url(r'^order/', include('order.urls', namespace='order')),]
    
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)
    
    

booksite/cart/urls.py
from django.conf.urls import url 
from .views import show_cart
urlpatterns =[
    url(r'^$', show_cart, name= 'show_cart'),
               ]

booksite/catalog/urls.py
from django.conf.urls import url
from .views import book_list, CategoryBookList ,book_detail

urlpatterns = [
    url(r'^$', book_list, name='book_list'),
    url(r'^(?P<slug>[\w\-]+)/$', book_detail , name='book_detail'),
    url(r'^categories/(?P<slug>[\w\-]+)/$', CategoryBookList.as_view(), name='books_by_category'),
    ]

booksite/order/urls.py
from django.conf.urls import url
from .views import order_create , order_detail

urlpatterns = [
    url(r'^create/$', order_create, name= 'create'),
    url(r'^(?P<order_id>[\w\-]+)/$', order_detail, name='order_detail'),
               ]

booksite/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^admin/', admin.site.urls),
        url(r'^books/', include('catalog.urls', namespace='catalog')),
        url(r'^accounts/', include('accounts.urls', namespace='accounts')),
        url(r'^__debug__/', include(debug_toolbar.urls)),
        url(r'^cart/', include('cart.urls', namespace= 'cart')),
        url(r'^order/', include('order.urls', namespace='order')),
        url(r'^i18n/', include('django.conf.urls.i18n')),
        ]
    
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)
    
    

booksite/cart/models.py
from django.db import models
from catalog.models import Book
import string
import random

class Cart(models.Model):
    cart_id = models.CharField(max_length=32, editable = False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    check_out = models.BooleanField(default= False)
    def save(self,*args, **kwargs):
        if not self.id:
            self.cart_id = ''.join([random.choice(string.ascii_letters+string.digits) for n in range(0,32)])
            super().save(*args,**kwargs)
            
    def __str__(self):
        return 'Cart: ' + str(self.cart_id)
    
class Item(models.Model):
    cart = models.ForeignKey(Cart)
    book = models.ForeignKey(Book)
    quantity = models.PositiveIntegerField()
    
    @property
    def unit_price(self):
        return self.book.price
    
    @property
    def total_price(self):
        return self.quantity*self.unit_price
    
    def __str__(self):
        return self.book.title
    

    
    

booksite/cart/forms.py
from django import forms
PRODUCT_QUANTITY_CHOICES =[(i,str(i)) for i in range(1,10000)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)

booksite/cart/views.py
from django.shortcuts import render
from cart.cart import Cart
from catalog.models import Book
from django.http.response import  HttpResponse
def show_cart(request):
    cart = Cart(request)
    if request.method == 'POST':
        postdata = request.POST.copy()
        if postdata['submit'] == 'Remove':
            item_id = postdata['item_id']
            cart.remove(item_id = item_id)
        if postdata['submit'] == 'Update':
            item_id = postdata['item_id']
            quantity = postdata['quantity']
            cart.update(item_id = item_id, quantity=quantity)    
    return render(request, 'cart/cart.html',{'cart':cart})


    

booksite/cart/templates/cart/base.html
{% load staticfiles %}
<html>
    <head>
        <title>{% block title%}Online Bookstore{% endblock %}</title>
        <meta charset='UTF-8'>
        <link rel="stylesheet" href="{% static 'css/base.css' %}?{% now "U" %}">
        <script src="http://libs.baidu.com/jquery/1.9.0/jquery.min.js"></script>
        {% block javascript %}{% endblock %}
    </head>
    <body>
        <div id='page'>
            <div id='header'>
                <div id='account-bar' class='cf'>
                    <div class='container'>
                        <div id='account-bar-status'>
                            {% if request.user.is_authenticated %}
                            <div class='account-bar-hello-user'>
                                <div class='account-bar-hello'>
                                    Hello {{ request.user.username }},
                                </div>
                                <a class='logout' href="{% url 'accounts:logout' %}">Logout</a>                        
                            </div>
                            {% else %}
                            <div class='account-bar-login-register'>
                                <a class='login' href="{% url 'accounts:login' %}">Login</a>
                                <div class='account-bar-divider'>|</div>
                                <a class='Register' href="{% url 'accounts:register' %}">Register</a>                       
                            </div>                    
                            {% endif %}
                        </div>
                    </div>                   
                </div>
                <div id='menu-bar' class='cf'>
                    <div class='container'>
                        <div id='menu-links'>
                            <div class='menu-item-tab'>
                                <a href="/">
                                    <span class='menu-logo'>Bookstore</span>
                                </a>                            
                            </div>                            
                            <div class='menu-item-tab'>
                                <a href="{% url 'catalog:book_list' %}">
                                    <span class='menu-text'>Books</span>
                                </a>                            
                            </div>
                            <div class='menu-item-tab'>
                                <a href="{% url 'cart:show_cart' %}">
                                    <span class='menu-text'>Cart</span>
                                </a>                            
                            </div>
                            <div class='menu-item-tab'>
                                <a href="{% url 'accounts:profile' %}">
                                    <span class='menu-text'>Account</span>
                                </a>                            
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div id='content' class='cf'>
                <div class='container cf'>
                {% block content %}
                {% endblock %}
                </div>
            </div>
            <div id='footer'>
                <div class='container'>
                    <div class='footer-main-block'>
                        <h2>Contact Us</h2>
                        <p>Get in touch here if you have any queries or issues.</p>
                    </div>
                    <div class='footer-main-block'>
                        <h2>Help & Support</h2>
                        <p>Click here for FAQs, order information, T&Cs, errata and code downloads</p>
                    </div>
                    <div class='footer-main-block'>
                        <h2>Alerts & Offers</h2>
                        <p>Sign up to our emails for regular updates, bespoke offers, exclusive discounts and great free content.</p>
                    </div>                    
                </div>
            </div>
        </div>
    </body>
</html>

booksite/cart/templates/cart/cart.html
{% extends "cart/base.html" %}
{% block javascript %}
<script type='text/javascript'>
	$('.deleteForm').submit(function(event){
		//stop form from submitting normally
		event.preventDefault();
		var item_id = $(this).children(':first').val();
		$.ajax({
			type:'POST',
			data:{'item_id':item_id},
		});
	});
	
	$('.updateForm').submit(function(event){
		//stop form from submitting normally
		event.preventDefault();
		var quantity = $(this).find("input[name='quantity']").val();
		var item_id = $(this).find("input[name='item_id']").val();
		$.ajax({
			type:'POST',
			data:{'item_id':item_id,
			'quantity':quantity}
		});
	});
	
</script>
{% endblock %}
{% block content %}
<div id='your-cart' class='cf'>
	<div class='left-pane'>
		<div class='inner'>
			<h1>Your shopping cart</h1>
			{% for item in cart %}
				{% with book=item.book %}
				<div id='item-{{ item.id }}' class='cart-product-line cf'>
					<div class='product-image float-left'>
						<a href='{{ book.get_absolute_url }}'>
							<img alt='Book Image' src='{{ book.img_url }}'>
						</a>
					</div>
					<div class='product-description float-left'>
						<div class='product-title'>
							<a href='{{ book.get_absolute_url }}'>
								<h2>{{ book.title }}</h2>
							</a>
						</div>
						<div class='author'>{{ book.author }}</div>
						<div class='price'>${{ book.price }}</div>
						<form class='updateForm float-left' action='' method='post'>
						{% csrf_token %}
						Quantity:
						<input class='quantity' type='number' name='quantity' pattern="[0-9]*" value='{{ item.quantity }}'/>
						<input type='hidden' name='item_id' value='{{ item.id}}'/>
						<input class='update' type='submit' name='submit' value='Update'/>
						</form>
						<form class='deleteForm' action="" method="post">
						{% csrf_token %}
						<input type='hidden' name='item_id' value='{{ item.id}}'/>
						<div class='float-right remove'>
							<button class='remove' type='submit' name='submit' value='Remove'>
								<span class="remove-icon"></span>
								Remove
							</button>
						</div>
						</form>																		
					</div>
				</div>
				{% endwith %}
			{% endfor %}
		</div>
	</div>
	<div class='right-pane'>
		<div id='cart-summary' class='checkout-pane cf'>
			<div class='summary-header cf'>
				<h2>Summary</h2>
			</div>
			<div id='cart-summary-body'>
				<div class='inner'>
					<div class='sub-total'>
						Total ({{ cart.sub_amount }} product{{ cart.sub_amount|pluralize }}): 
						<span class='price'>${{ cart.sub_price }}</span>
					</div>					
					<a href="{% url 'order:create' %}">
						<div class='checkout button'>CheckOut</div>
					</a>									
				</div>					
			</div>
		</div>
	</div>
</div>
{% endblock %}